Add  support for new  Xray graph scan API
jfrog/jfrog-idea-plugin pull request #146
Opened 2021-09-26 07:42 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-idea-plugin/actions/workflows/test.yml) passed. If this feature is not already covered by the tests, I added new tests.
-----

2021-09-29 15:54 UTC, eyalbe4 requested changes

2021-09-29 15:54 UTC, eyalbe4 commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +            if (GraphScanLogic.isXrayVersionSupported(client.system().version())) {
isXrayVersionSupported --> isSupportedInXrayVersion

2021-09-29 15:54 UTC, eyalbe4 commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +        } catch (IOException e) {
Better not to catch the exception, but let it be thrown. We should strive to catch them in upper most part of the stack trace as possible. The code is "healthier" this way.

2021-09-29 15:54 UTC, eyalbe4 commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +                if (BulkScanLogic.isXrayVersionSupported(client.system().version())) {
If we got here, it means that we already sent a "get version" request to Xray, and now we're sending it again. Let's sent this request only once in the beginning.

2021-09-29 15:54 UTC, eyalbe4 commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +    private static final Path HOME_PATH = Paths.get(System.getProperty("user.home"), ".jfrog-idea-plugin");
The above variable is retrieved multiple times in the code, so the following is duplicated - 
```
Paths.get(System.getProperty("user.home"), ".jfrog-idea-plugin");
```
Let's create a utility method or methods (in Utils), to retrieve all the needed directories under the user home.

2021-09-30 18:33 UTC, yahavi requested changes
* Please make sure to run reformat and organize imports on all changed files (I missed some in the review)
* The project configuration should be also reflected in ConfigurationTest

2021-09-30 18:33 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
> +            if (!isSupportedInXrayVersion(xrayVersion)) {
Looks like a compilation issue here

2021-09-30 18:33 UTC, yahavi commented on src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
> +
```suggestion
```

2021-09-30 18:33 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +     * Start a Xray scan for all projects.
```suggestion
     * Start an Xray scan for all projects.
```

2021-09-30 18:33 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> +        }
```suggestion
        } 
        if (ComponentSummaryScanLogic.isSupportedInXrayVersion(xrayVersion)) {
            return new ComponentSummaryScanLogic(scanCache, log);
        }
```

2021-09-30 18:33 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
> +
```suggestion
```

2021-09-30 18:33 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/utils/Utils.java
> +
```suggestion
```

2021-10-03 06:58 UTC, merged