Allow creating ignore rules to specific violation
jfrog/jfrog-idea-plugin pull request #281
Opened 2023-01-23 15:14 UTC by talarian1

- [ ] All [tests](https://github.com/jfrog/jfrog-idea-plugin/actions/workflows/test.yml) passed. If this feature is not already covered by the tests, I added new tests.
-----
Added the option to create ignore rule in the right-click context menu.
Fixes https://github.com/jfrog/jfrog-idea-plugin/issues/238
Depends on https://github.com/jfrog/ide-plugins-common/pull/103

After right-click:

![Screenshot 2023-01-23 at 17 13 52](https://user-images.githubusercontent.com/24526180/214075706-eda48635-22ac-4df7-a744-f8fe818b7303.png)

When no project/watch was configured so the ignore rule cannot be created:

![2](https://user-images.githubusercontent.com/24526180/215731911-f70b7f89-dfc6-4db0-a53f-4cbaf82bbd2f.png)

2023-01-24 08:20 UTC, asafgabai requested changes

2023-01-24 08:43 UTC, yahavi requested changes

2023-01-24 08:43 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
> +        this.setEnabled(isNotBlank(this.ignoreRuleUrl));
Let's open the settings when no watch or project are configured

2023-01-24 08:43 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> +    private static final String IGNORE_RULE_TOOL_TIP = "Create ignore rule option is only available if JFrog Project or watches are defined";
I think this tooltip doesn't appear when the button is disabled
```suggestion
    private static final String IGNORE_RULE_TOOL_TIP = "Create ignore rule option is only available if JFrog Project or Watches are defined";
```

2023-01-24 08:43 UTC, yahavi commented on src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> +        popupMenu.setFocusable(false);
Shouldn't setFocusable happen after the creation of the popupMenu?

2023-02-07 14:36 UTC, asafgabai requested changes

2023-02-07 14:36 UTC, asafgabai commented on src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
> +                                if (!(event.getEventType() == ACTIVATED)) {
if (!(event.getEventType() == ACTIVATED))
-->
if (event.getEventType() != ACTIVATED)

2023-02-07 14:36 UTC, asafgabai commented on src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> +        popupMenu.add( new CreateIgnoreRuleAction(selectedIssue.getIgnoreRuleUrl(), mouseEvent));
🙈
```suggestion
        popupMenu.add(new CreateIgnoreRuleAction(selectedIssue.getIgnoreRuleUrl(), mouseEvent));
```

2023-02-08 10:46 UTC, merged