New feature - Suggest Gradle (groovy and kotlin) fix vulnerable version
jfrog/jfrog-idea-plugin pull request #301
Opened 2023-02-23 12:42 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-idea-plugin/actions/workflows/test.yml) passed. If this feature is not already covered by the tests, I added new tests.
-----

2023-03-02 15:14 UTC, talarian1 reviewed
The flowing README line should be updated as well:

> | Upgrade vulnerable dependencies to fixed versions   |  ✅  |   ✅   |   ❌    |  ✅  |    ✅    |   ❌    |

2023-03-05 17:10 UTC, yahavi requested changes
Looks good! 
Let's add some tests to the UpgradeVersion classes to make the code bulletproof now and in the future.
Can be added in a different PR.

2023-03-05 17:45 UTC, sverdlov93 commented on README.md
> +| Contextual Analysis (requires Xray 3.66.5 or above) |  ❌  |   ❌   |       ❌       |       ❌       |  ✅  |    ❌    |   ✅    |
@asafgabai What do you think?

2023-03-05 17:56 UTC, sverdlov93 commented on src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
> -        }
it also had a code repetition before that, in line 72 and here and I needed the component name outside the function.

2023-03-05 17:56 UTC, sverdlov93 commented on src/main/java/com/jfrog/ide/idea/inspections/GradleKotlinInspection.java
> +                if (((KtFile) list.getContainingFile()).isScript()) {
To Verify that the visited file is a `build.gradle.kts` file. otherwise, it's visiting all kotlin files in the IDE.
I added a comment.

2023-03-07 13:37 UTC, merged